### ISSUE TITLE
Recipe Page: SQL Database

### ISSUE THREAD

**Issue by miskiabdirizak** [miskiabdirizak/Recipe-App#1]
###Goal: 
When a user inputs their ingredients they need to be able to see a list of recipes that will match the ingredients they inputted and fit into their dietary/fitness goals. As such we need to implement a SQL database that will store the recipe details. 

###Tasks: 

- [ ] Create an ER Model for SQL database 
- [ ] Convert ER Model to a Relational Model 
- [ ] Translate Relational Model into SQL 
- [ ] Web Scrap websites for Recipes
- [ ] Save Scrapped data into SQL Database

###Implementation Tools: 

- Introduction To Database Systems (Slides on Icollege) 
- https://www.youtube.com/watch?v=QpdhBUYk7Kk
- https://www.youtube.com/watch?v=OwdFzygGZqk
