### ISSUE TITLE
#recipe app Project Set up: Configuring Github

### ISSUE THREAD

**Issue by miskiabdirizak** [miskiabdirizak/Recipe-App#4]

**Comment by miskiabdirizak** [comment]
## Goal: 

The user should be able to input a username and password. These credentials should match the ones we have in the SQL Database, which will verify that this is the correct user. If the username and password are incorrect then an error message should be shown, denying the user to continue to the home page. If the credentials are correct then the user should be able to continue to the home page.

## Tasks 
### Front-end
- [ ]  Use HTML to create an input form with 2 inputs: username and password
- [ ] Password should be encrypted with dots when entering the field 


### Backend 
- [ ] Use JavaScript to create API calls to the database to determine if the credentials the user inputted match the ones in the database
- [ ] Link login page to move to the home screen if credentials are correct 
- [ ] *** EXTRA FUNCTION: Forgot password => could be another story 

## Tools: 

-  https://www.youtube.com/watch?v=tGeEYl176ks
- https://javascript.plainenglish.io/creating-a-sign-up-form-in-react-with-typescript-516b1a172913
