### ISSUE TITLE
Authentification: Create an account Page

### ISSUE THREAD

**Issue by miskiabdirizak** [miskiabdirizak/Recipe-App#6]

**Comment by miskiabdirizak** [comment]
## Goals: 
A new user should be able to create a new user profile/ account with our application. The user should input their email, a unique username, and a unique password.

## Tasks and Specifications: 
### Front-End: 
- [ ] HTML form with 4 inputs: Email, Username, Password, Confirm Password
- [ ] Password should be encrypted while typing 
### Back-End: 
- [ ] User inputs should be stored in a USER table within the SQL Database 
- [ ] User inputs should not match those inside the database. 
- [ ] Username and Password should have specific constraints in order to be created: Use of special letters, capitalization, numbers, and string-length
- [ ] Once the account is created, the page should move into either the login page or the home page

## Tools: 
- https://www.youtube.com/watch?v=ptb94bVWD3U
